# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ark < Formula
  desc "Yet another alternate [directory | repository] represent text generator tool"
  homepage "https://github.com/magicdrive/ark"
  version "0.2.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/magicdrive/ark/releases/download/v0.2.1/ark_0.2.1_darwin_amd64.tar.gz"
      sha256 "0c143e7b0f4ac001142a9147fc35a6716cdc8e878629b451b3752ae88c95d501"

      def install
        bin.install "ark"
        bash_completion.install "completions/bash/ark-completion.bash" => "ark"
        zsh_completion.install "completions/zsh/_ark" => "_ark"
      end
    end
    on_arm do
      url "https://github.com/magicdrive/ark/releases/download/v0.2.1/ark_0.2.1_darwin_arm64.tar.gz"
      sha256 "ba1cab7b637f6eb6679619360773cdece1eec284866d6d789749122e40fce5d2"

      def install
        bin.install "ark"
        bash_completion.install "completions/bash/ark-completion.bash" => "ark"
        zsh_completion.install "completions/zsh/_ark" => "_ark"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/magicdrive/ark/releases/download/v0.2.1/ark_0.2.1_linux_amd64.tar.gz"
        sha256 "2efc980c7af338d9e2f989671e795775350ea0980703c4ddaa62fa1557dfc931"

        def install
          bin.install "ark"
          bash_completion.install "completions/bash/ark-completion.bash" => "ark"
          zsh_completion.install "completions/zsh/_ark" => "_ark"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/magicdrive/ark/releases/download/v0.2.1/ark_0.2.1_linux_arm64.tar.gz"
        sha256 "ab1e7b027d76e84fc9cd09d6bd94cd26c493262705478950e26198e1b8b80c5a"

        def install
          bin.install "ark"
          bash_completion.install "completions/bash/ark-completion.bash" => "ark"
          zsh_completion.install "completions/zsh/_ark" => "_ark"
        end
      end
    end
  end

  test do
    system "#{bin}/ark", "--version"
  end
end
