# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ark < Formula
  desc "Yet another alternate [directory | repository] text generator tool — with code intelligence MCP tools"
  homepage "https://github.com/magicdrive/ark"
  version "3.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/magicdrive/ark/releases/download/v3.1.0/ark_3.1.0_darwin_amd64.tar.gz"
      sha256 "6cc0e0ca0b335127490c5ed13054bcd1e6df9679599325d147a4e18704bac98e"

      def install
        bin.install "ark"
        bash_completion.install "completions/bash/ark-completion.bash" => "ark"
        zsh_completion.install "completions/zsh/_ark" => "_ark"
        fish_completion.install "completions/fish/ark.fish" => "ark.fish"
      end
    end
    on_arm do
      url "https://github.com/magicdrive/ark/releases/download/v3.1.0/ark_3.1.0_darwin_arm64.tar.gz"
      sha256 "7fcabd86f076e1f6660038df02a8441daf2e22fe68757415d71180d105bd47c5"

      def install
        bin.install "ark"
        bash_completion.install "completions/bash/ark-completion.bash" => "ark"
        zsh_completion.install "completions/zsh/_ark" => "_ark"
        fish_completion.install "completions/fish/ark.fish" => "ark.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/magicdrive/ark/releases/download/v3.1.0/ark_3.1.0_linux_amd64.tar.gz"
        sha256 "c199abbaa74e670fa19979965ce5664df5197e1b91b64fb99193920ba66393c1"

        def install
          bin.install "ark"
          bash_completion.install "completions/bash/ark-completion.bash" => "ark"
          zsh_completion.install "completions/zsh/_ark" => "_ark"
          fish_completion.install "completions/fish/ark.fish" => "ark.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/magicdrive/ark/releases/download/v3.1.0/ark_3.1.0_linux_arm64.tar.gz"
        sha256 "e48495c1435019608b4ca4e0ed6b06f4dad1d9c2d7e2989768f7f0ada9e68444"

        def install
          bin.install "ark"
          bash_completion.install "completions/bash/ark-completion.bash" => "ark"
          zsh_completion.install "completions/zsh/_ark" => "_ark"
          fish_completion.install "completions/fish/ark.fish" => "ark.fish"
        end
      end
    end
  end

  test do
    system "#{bin}/ark", "--version"
  end
end
