# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ark < Formula
  desc "Yet another alternate [directory | repository] text generator tool — with code intelligence MCP tools"
  homepage "https://github.com/magicdrive/ark"
  version "4.1.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/magicdrive/ark/releases/download/v4.1.1/ark_4.1.1_darwin_amd64.tar.gz"
      sha256 "c128b87bad97a49942664ac5bc8f3ccc55e8378549c974125b5c6ffd7e26ae5d"

      def install
        bin.install "ark"
        bash_completion.install "completions/bash/ark-completion.bash" => "ark"
        zsh_completion.install "completions/zsh/_ark" => "_ark"
        fish_completion.install "completions/fish/ark.fish" => "ark.fish"
      end
    end
    on_arm do
      url "https://github.com/magicdrive/ark/releases/download/v4.1.1/ark_4.1.1_darwin_arm64.tar.gz"
      sha256 "3acf9e9793b2c165f924f0cc217ffd70a8745c5d99d6d725501c631f9f5244d6"

      def install
        bin.install "ark"
        bash_completion.install "completions/bash/ark-completion.bash" => "ark"
        zsh_completion.install "completions/zsh/_ark" => "_ark"
        fish_completion.install "completions/fish/ark.fish" => "ark.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/magicdrive/ark/releases/download/v4.1.1/ark_4.1.1_linux_amd64.tar.gz"
        sha256 "e9490b64de813633f80768b4f841bbf1a3bc28ee480f3a472239c882eb3a48db"

        def install
          bin.install "ark"
          bash_completion.install "completions/bash/ark-completion.bash" => "ark"
          zsh_completion.install "completions/zsh/_ark" => "_ark"
          fish_completion.install "completions/fish/ark.fish" => "ark.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/magicdrive/ark/releases/download/v4.1.1/ark_4.1.1_linux_arm64.tar.gz"
        sha256 "85a6dba91c9b7e52e53150cad3f2df5061f8655335c8bdde8badb5358643c8f9"

        def install
          bin.install "ark"
          bash_completion.install "completions/bash/ark-completion.bash" => "ark"
          zsh_completion.install "completions/zsh/_ark" => "_ark"
          fish_completion.install "completions/fish/ark.fish" => "ark.fish"
        end
      end
    end
  end

  test do
    system "#{bin}/ark", "--version"
  end
end
