# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Enma < Formula
  desc "Yet another integration software with file monitoring."
  homepage "https://github.com/magicdrive/enma"
  version "1.2.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/magicdrive/enma/releases/download/v1.2.9/enma_1.2.9_darwin_amd64.tar.gz"
      sha256 "7a0e92f36b666670002981e5d5fdc584de7c409a1e1ec137ccedcdb1d7ec18c6"

      define_method(:install) do
        bin.install "enma"
        bash_completion.install "completions/bash/enma-completion.bash" => "enma"
        zsh_completion.install "completions/zsh/_enma" => "_enma"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/magicdrive/enma/releases/download/v1.2.9/enma_1.2.9_darwin_arm64.tar.gz"
      sha256 "b77719055ef6e85239e5e9ba5310cce97ebadbb4cdfaaa13e637117f380277ad"

      define_method(:install) do
        bin.install "enma"
        bash_completion.install "completions/bash/enma-completion.bash" => "enma"
        zsh_completion.install "completions/zsh/_enma" => "_enma"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/magicdrive/enma/releases/download/v1.2.9/enma_1.2.9_linux_amd64.tar.gz"
      sha256 "4baf9e42ce3756a53ebb22c4117a0be264f0b5f689960dc24f190fee4ca9b4bb"
      define_method(:install) do
        bin.install "enma"
        bash_completion.install "completions/bash/enma-completion.bash" => "enma"
        zsh_completion.install "completions/zsh/_enma" => "_enma"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/magicdrive/enma/releases/download/v1.2.9/enma_1.2.9_linux_arm64.tar.gz"
      sha256 "9dd58d13ec7244ffc5b73a434ebc6c3c29f148f93a1d44105a5b8ef89777e193"
      define_method(:install) do
        bin.install "enma"
        bash_completion.install "completions/bash/enma-completion.bash" => "enma"
        zsh_completion.install "completions/zsh/_enma" => "_enma"
      end
    end
  end

  test do
    system "#{bin}/enma", "--version"
  end
end
