# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Enma < Formula
  desc "Yet another integration software with file monitoring."
  homepage "https://github.com/magicdrive/enma"
  version "1.2.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/magicdrive/enma/releases/download/v1.2.0/enma_1.2.0_darwin_amd64.tar.gz"
      sha256 "f6fcc05c860fba80e333a56d61d54282eb7cdca4c465603380331e8ab6bb45d9"

      def install
        bin.install "enma"
        bash_completion.install "completions/bash/enma-completion.bash" => "enma"
        zsh_completion.install "completions/zsh/_enma" => "_enma"
      end
    end
    on_arm do
      url "https://github.com/magicdrive/enma/releases/download/v1.2.0/enma_1.2.0_darwin_arm64.tar.gz"
      sha256 "b034b7c8b583404fe5820c757e0854bfc1d8483b92ac3210d835984ccfd6b173"

      def install
        bin.install "enma"
        bash_completion.install "completions/bash/enma-completion.bash" => "enma"
        zsh_completion.install "completions/zsh/_enma" => "_enma"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/magicdrive/enma/releases/download/v1.2.0/enma_1.2.0_linux_amd64.tar.gz"
        sha256 "2a5c29f6c95cd40103e937a0fbab7274822b2ce3ee24f17dd9d42fb9b146e542"

        def install
          bin.install "enma"
          bash_completion.install "completions/bash/enma-completion.bash" => "enma"
          zsh_completion.install "completions/zsh/_enma" => "_enma"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/magicdrive/enma/releases/download/v1.2.0/enma_1.2.0_linux_arm64.tar.gz"
        sha256 "ee44ca039ba7f2ae3642822bb4b388c75f18e037ffa0b02b44a84753f12a0990"

        def install
          bin.install "enma"
          bash_completion.install "completions/bash/enma-completion.bash" => "enma"
          zsh_completion.install "completions/zsh/_enma" => "_enma"
        end
      end
    end
  end

  test do
    system "#{bin}/enma", "--version"
  end
end
