# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goreg < Formula
  desc "Yet another alternate `goimports` tool."
  homepage "https://github.com/magicdrive/goreg"
  version "1.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/magicdrive/goreg/releases/download/v1.3.1/goreg_1.3.1_darwin_amd64.tar.gz"
      sha256 "12a45d3002b1ec540cd04a34d9dd28b2702db23daf297d5dd0130192ebe4b950"

      define_method(:install) do
        bin.install "goreg"
        bash_completion.install "completions/bash/goreg-completion.bash" => "goreg"
        zsh_completion.install "completions/zsh/_goreg" => "_goreg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/magicdrive/goreg/releases/download/v1.3.1/goreg_1.3.1_darwin_arm64.tar.gz"
      sha256 "a5598d3013c412e54cb2c1645cd0fa3cc25471e2029fed45172891f4cca0b641"

      define_method(:install) do
        bin.install "goreg"
        bash_completion.install "completions/bash/goreg-completion.bash" => "goreg"
        zsh_completion.install "completions/zsh/_goreg" => "_goreg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/magicdrive/goreg/releases/download/v1.3.1/goreg_1.3.1_linux_amd64.tar.gz"
      sha256 "4f07fc81323c309c9bf8d51071a583252694c05576d5d943330b76a48315a3e1"
      define_method(:install) do
        bin.install "goreg"
        bash_completion.install "completions/bash/goreg-completion.bash" => "goreg"
        zsh_completion.install "completions/zsh/_goreg" => "_goreg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/magicdrive/goreg/releases/download/v1.3.1/goreg_1.3.1_linux_arm64.tar.gz"
      sha256 "c56d1c01ea3c7e8f3b8dffc4052a3e0f6e370e05dfdb5cda6391facbd1c3f891"
      define_method(:install) do
        bin.install "goreg"
        bash_completion.install "completions/bash/goreg-completion.bash" => "goreg"
        zsh_completion.install "completions/zsh/_goreg" => "_goreg"
      end
    end
  end

  test do
    system "#{bin}/goreg", "--version"
  end
end
