# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goreg < Formula
  desc "Yet another alternate `goimports` tool."
  homepage "https://github.com/magicdrive/goreg"
  version "1.3.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/magicdrive/goreg/releases/download/v1.3.8/goreg_1.3.8_darwin_amd64.tar.gz"
      sha256 "d6a1a6070a6ae0748e0dc208054fb00a89a5b804593e2acc9bcd52bf63ff9f2b"

      define_method(:install) do
        bin.install "goreg"
        bash_completion.install "completions/bash/goreg-completion.bash" => "goreg"
        zsh_completion.install "completions/zsh/_goreg" => "_goreg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/magicdrive/goreg/releases/download/v1.3.8/goreg_1.3.8_darwin_arm64.tar.gz"
      sha256 "c2108de2faf2839cdf4bba2efdbc3bc84c6ceabbe2ebff1c4128c80acccd76d4"

      define_method(:install) do
        bin.install "goreg"
        bash_completion.install "completions/bash/goreg-completion.bash" => "goreg"
        zsh_completion.install "completions/zsh/_goreg" => "_goreg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/magicdrive/goreg/releases/download/v1.3.8/goreg_1.3.8_linux_amd64.tar.gz"
      sha256 "8c589775874f9bd3aa6db93e83666c400aad236108f6c6b459c2e495c365d5f6"
      define_method(:install) do
        bin.install "goreg"
        bash_completion.install "completions/bash/goreg-completion.bash" => "goreg"
        zsh_completion.install "completions/zsh/_goreg" => "_goreg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/magicdrive/goreg/releases/download/v1.3.8/goreg_1.3.8_linux_arm64.tar.gz"
      sha256 "98be8f65b45af5b08560658a0ae8e526344d0c3cfd29bcf153340b2f7de0e332"
      define_method(:install) do
        bin.install "goreg"
        bash_completion.install "completions/bash/goreg-completion.bash" => "goreg"
        zsh_completion.install "completions/zsh/_goreg" => "_goreg"
      end
    end
  end

  test do
    system "#{bin}/goreg", "--version"
  end
end
