# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goreg < Formula
  desc "Yet another alternate `goimports` tool."
  homepage "https://github.com/magicdrive/goreg"
  version "1.2.5"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/magicdrive/goreg/releases/download/v1.2.5/goreg_1.2.5_darwin_amd64.tar.gz"
      sha256 "c49a90a5b652f875e8b064fa44f88e70faa396c4e3adbe866ab87919e0939c6d"

      def install
        bin.install "goreg"
        bash_completion.install "completions/bash/goreg-completion.bash" => "goreg"
        zsh_completion.install "completions/zsh/_goreg" => "_goreg"
      end
    end
    on_arm do
      url "https://github.com/magicdrive/goreg/releases/download/v1.2.5/goreg_1.2.5_darwin_arm64.tar.gz"
      sha256 "50b922538dcebe46436ccc2ada4d2617e17d264e9f536a87b64f0e22dcbfb45d"

      def install
        bin.install "goreg"
        bash_completion.install "completions/bash/goreg-completion.bash" => "goreg"
        zsh_completion.install "completions/zsh/_goreg" => "_goreg"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/magicdrive/goreg/releases/download/v1.2.5/goreg_1.2.5_linux_amd64.tar.gz"
        sha256 "c978c2ccf7036827459a1a5f335de1348076baa9e5c7f9d895d977a02da99e23"

        def install
          bin.install "goreg"
          bash_completion.install "completions/bash/goreg-completion.bash" => "goreg"
          zsh_completion.install "completions/zsh/_goreg" => "_goreg"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/magicdrive/goreg/releases/download/v1.2.5/goreg_1.2.5_linux_arm64.tar.gz"
        sha256 "c99d7aadc33829efd6c8ce4379a0312a94a048df6f540beae644cb30ee7a4438"

        def install
          bin.install "goreg"
          bash_completion.install "completions/bash/goreg-completion.bash" => "goreg"
          zsh_completion.install "completions/zsh/_goreg" => "_goreg"
        end
      end
    end
  end

  test do
    system "#{bin}/goreg", "--version"
  end
end
