# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kirke < Formula
  desc "Yet another command-line tool for converting JSON strings into Golang struct definitions."
  homepage "https://github.com/magicdrive/kirke"
  version "1.2.7"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/magicdrive/kirke/releases/download/v1.2.7/kirke_1.2.7_darwin_amd64.tar.gz"
      sha256 "37006832135436e1df241dec25aef9d4885ad4bb0eef2895872de97cc5fe7775"

      def install
        bin.install "kirke"
        cp "completions/kirke-completion.sh", "completions/kirke.zsh"

        bash_completion.install "completions/kirke-completion.sh" => "kirke"
        zsh_completion.install "completions/kirke.zsh" => "_kirke"
      end
    end
    on_arm do
      url "https://github.com/magicdrive/kirke/releases/download/v1.2.7/kirke_1.2.7_darwin_arm64.tar.gz"
      sha256 "36a88f86f0f176a0318e69498c09f2729e971cccd95216a06f22ed5303ee0ebe"

      def install
        bin.install "kirke"
        cp "completions/kirke-completion.sh", "completions/kirke.zsh"

        bash_completion.install "completions/kirke-completion.sh" => "kirke"
        zsh_completion.install "completions/kirke.zsh" => "_kirke"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/magicdrive/kirke/releases/download/v1.2.7/kirke_1.2.7_linux_amd64.tar.gz"
        sha256 "9630ec243138aac8ebd69877657c814b89396960dc6662c1ed52401d28f13835"

        def install
          bin.install "kirke"
          cp "completions/kirke-completion.sh", "completions/kirke.zsh"

          bash_completion.install "completions/kirke-completion.sh" => "kirke"
          zsh_completion.install "completions/kirke.zsh" => "_kirke"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/magicdrive/kirke/releases/download/v1.2.7/kirke_1.2.7_linux_arm64.tar.gz"
        sha256 "03c6a8a494b401f8529d758d109a8268af59134fa59ba02a73bdc9cc7724cb45"

        def install
          bin.install "kirke"
          cp "completions/kirke-completion.sh", "completions/kirke.zsh"

          bash_completion.install "completions/kirke-completion.sh" => "kirke"
          zsh_completion.install "completions/kirke.zsh" => "_kirke"
        end
      end
    end
  end

  test do
    system "#{bin}/kirke", "--version"
  end
end
