# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kirke < Formula
  desc "Yet another command-line tool for converting JSON strings into Golang struct definitions."
  homepage "https://github.com/magicdrive/kirke"
  version "1.2.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/magicdrive/kirke/releases/download/v1.2.2/kirke_1.2.2_darwin_amd64.tar.gz"
      sha256 "6fc35ff94a2427baa4d996b76f55b5014181820dbc81900790c397a68b0edaa3"

      def install
        bin.install "kirke"
      end
    end
    on_arm do
      url "https://github.com/magicdrive/kirke/releases/download/v1.2.2/kirke_1.2.2_darwin_arm64.tar.gz"
      sha256 "f21412fddb6508ab129859cce9717716b755e97627bca5c43604a484bc4e0da0"

      def install
        bin.install "kirke"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/magicdrive/kirke/releases/download/v1.2.2/kirke_1.2.2_linux_amd64.tar.gz"
        sha256 "3fa208e42cd3bd03385a641348bb9a0765fa1b975b5e89af49492c640ffcb1c6"

        def install
          bin.install "kirke"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/magicdrive/kirke/releases/download/v1.2.2/kirke_1.2.2_linux_arm64.tar.gz"
        sha256 "0acf56e5fe7699681f82287c60cc8aeead32da6bf03a150a00db56fcc3f96199"

        def install
          bin.install "kirke"
        end
      end
    end
  end

  test do
    system "#{bin}/kirke", "--version"
  end
end
