# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kirke < Formula
  desc "Yet another command-line tool for converting JSON strings into Golang struct definitions."
  homepage "https://github.com/magicdrive/kirke"
  version "1.2.6"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/magicdrive/kirke/releases/download/v1.2.6/kirke_1.2.6_darwin_amd64.tar.gz"
      sha256 "0793fe8e2f01b3a31b37a1629b9926a4d9d00b3bd22bd29cec097b6928d51dbf"

      def install
        bin.install "kirke"
        bash_completion.install "completions/kirke-completion.sh" => "kirke"
        zsh_completion.install "completions/kirke-completion.sh"
      end
    end
    on_arm do
      url "https://github.com/magicdrive/kirke/releases/download/v1.2.6/kirke_1.2.6_darwin_arm64.tar.gz"
      sha256 "aa9dd5fb093f7d3cb601fb79be07bff90d882a70e96a57060ad11cec148a53a9"

      def install
        bin.install "kirke"
        bash_completion.install "completions/kirke-completion.sh" => "kirke"
        zsh_completion.install "completions/kirke-completion.sh"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/magicdrive/kirke/releases/download/v1.2.6/kirke_1.2.6_linux_amd64.tar.gz"
        sha256 "b544d680ddc340bf5b1a31c7f7d1aa4e553ed47d7ded1592eee17a97addb22e2"

        def install
          bin.install "kirke"
          bash_completion.install "completions/kirke-completion.sh" => "kirke"
          zsh_completion.install "completions/kirke-completion.sh"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/magicdrive/kirke/releases/download/v1.2.6/kirke_1.2.6_linux_arm64.tar.gz"
        sha256 "efa3dfb7a7b3b3138aa3f7a126e9e3c5c2b532a623ba6bdf5f807380163fb169"

        def install
          bin.install "kirke"
          bash_completion.install "completions/kirke-completion.sh" => "kirke"
          zsh_completion.install "completions/kirke-completion.sh"
        end
      end
    end
  end

  test do
    system "#{bin}/kirke", "--version"
  end
end
